apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tomcat
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
        - name: my-tomcat-container
          image: bhargavmo14/kubernetes:1.0
          ports:
            - containerPort: 8080
