apiVersion: v1
kind: Service
metadata:
  name: my-tomcat-service
spec:
  selector:
    app: my-tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30070
  type: NodePort
